### ISSUE TITLE
Message has no body

### ISSUE THREAD

**Issue by ilario** [jikamens/undigestify#1]
Both using the 2.0.0 version and compiling Undigestify from source, I get this message when trying to unpack a digest mail from [openwrt-devel list](https://lists.infradead.org/mailman/listinfo/openwrt-devel):

`Undigestify: Message has no body`

**Comment by jikamens** [comment]
Wow, someone is actually using this add-on? Amazing. ;-)
Can you save the offending message and attach the EML file to this issue?

**Comment by ilario** [comment]
Yesss, this add-on is very useful, in my opinion! Thanks for developing it!
Attached is the zipped EML file (Github didn't like `.eml`).
I am using Thunderbird 68.3.1 (64-bit)
[openwrt-develDigest.zip](https://github.com/jikamens/undigestify/files/4040631/openwrt-develDigest.zip)

**Comment by jikamens** [comment]
Fixed in version 2.0.1. You can wait until the editors of addons.thunderbird.net approve the new version and then you'll get the update when Thunderbird checks for add-on updates, or before then you can download it from [here](https://addons.thunderbird.net/thunderbird/downloads/file/1016310/undigestify-2.0.1-tb.xpi). Sorry about the trouble.

**Comment by ilario** [comment]
Works perfectly!
Thank you very much :D
